# Generated by Django 4.1.2 on 2022-10-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudst',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
