# Generated by Django 4.1.2 on 2022-10-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_crudst_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudst',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
