# Generated by Django 4.1.2 on 2022-10-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_crudst_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crudst',
            old_name='staddress',
            new_name='fromdes',
        ),
        migrations.RenameField(
            model_name='crudst',
            old_name='stemail',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='crudst',
            old_name='stname',
            new_name='todes',
        ),
    ]
