# Generated by Django 4.1.2 on 2022-10-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_staddress_crudst_fromdes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudst',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=100, null=True),
        ),
    ]
